version: 2.1

jobs:
  build:
    working_directory: ~/circleci-golang
    docker:
      - image: "circleci/golang"
    steps:
      - checkout
      - run: go run 01hello/main.go
      - run: go run 02variables/main.go
      - run: go run 03userinput/main.go
      - run: go run 04conversion/main.go

workflows:
  build_and_test:
    jobs:
      - build